### ISSUE TITLE
Error if no direction is selected

### ISSUE THREAD

**Issue by Kriechi** [tapnair/NESTER#1]
Thanks for the awesome script! I just found it and wanted to test a few things.

If I do not select a direction, and simply click OK, the script crashes with the following error:
`RuntimeError 3: invalid argument index`
<img width="406" alt="screen shot 2016-08-20 at 12 37 24" src="https://cloud.githubusercontent.com/assets/114300/17830689/5cb2be4c-66d3-11e6-9422-265df1878399.png">

I would have expected a more graceful error handling, e.g. either disable the OK button until all three things are filled out properly, or display a better error message.

**Comment by tapnair** [comment]
Good call. I think after i updated it from a script to an add-in this is taken care of.  It won't let you hit ok until the edge is selected now.
