### ISSUE TITLE
Error if components are fully jointed

### ISSUE THREAD

**Issue by Kriechi** [tapnair/NESTER#2]
All my components are fully defined and fixed together with joints.
This means they are not allowed to move in any directions.

If I try to run NESTER on these components I get the following error message:
`RuntimeError 5: A joint in system exsists [sic!] for the provided input. System will be overconstrined [sic!] with this input.`
<img width="406" alt="screen shot 2016-08-20 at 12 41 44" src="https://cloud.githubusercontent.com/assets/114300/17830696/98f65c60-66d3-11e6-8b92-c56f0488b21b.png">

Is there any way to disable or override these joints?
It would be really great of running NESTER could be reversed, e.g. if I want to make changes to my components, and then re-run NESTER to lay everything flat.

**Comment by tapnair** [comment]
There is not a way to do this elegantly.  I think the best way is to actually make a copy of the components into a sub assembly first before nesting so you can view in both orientations.  

The latest version has this as an option although in some cases the gaps are not calculating quite right if this option is checked.  

Probably best to create the sub assembly manually and then flatten.
