### ISSUE TITLE
Default selection for base face?

### ISSUE THREAD

**Issue by Kriechi** [tapnair/NESTER#3]
Is it possible to have a default selection for the base face?
E.g. default to flatten everything onto the XZ plane?

**Comment by tapnair** [comment]
Good idea, but I think it would make more sense for it to be XY plane?  There is an option in your user settings to have "Z up" which probably makes most sense for this type of work.

**Comment by tapnair** [comment]
I looked into this and because of the way I am creating mates it won't work.  You need to have a physical component anchored to create the joints to.  You can't create joints to the assy planes unfortunately.

Maybe I could set it up where it remembers your last selection in a given model though.
