### ISSUE TITLE
Moving parts when creating a sub-assembly 

### ISSUE THREAD

**Issue by mtchturner** [tapnair/NESTER#7]
Hi, 

I have found that when I run this add on and select 'create sub-assembly',  I am unable to move the components when they have been layed flat. 
When I select the individual components and attempt to move it, the entire nested assembly moves

I have tried playing with the selection filters with the same result 

Is there something I am missing?

**Comment by tapnair** [comment]
Latest version now hides the option, thanks again for the reminder.

**Comment by mtchturner** [comment]
Hey man, 
No worries...  I've updated to the latest version but am still having the same drama
I find I'm able to move one piece once, then every subsequent move will grab everything that was just layed flat, plus the base object 
Sorry to be a pain, I'm sure it's something I'm doing wrong
